### ISSUE TITLE
64 bit key is not enough

### ISSUE THREAD

**Issue by ValleZ** [RovoMe/JDrum#1]
Original algorithm uses 80 bit. When you deal with data what can hash into 64 bit with almost no collisions you probably should store all the data in RAM.

**Comment by RovoMe** [comment]
Thank you for your input. As I have no access to the original DRUM implementation (or at least have no link available) the implementation is more or less based on my understanding of the paper. If you can point me to the 80 bit key length within the paper or the original source I'd be grateful.

Maybe generifying the key with `? extends Number` would make sense to support either integer, long or even larger keys if needed. This however also puts additional burden into the de/serialization process of respecting the actual key type length. This is doable for sure and I might have a look into it when I find time and also find the motivation to do it.

**Comment by ValleZ** [comment]
Seems I was about different algorithm, I've rechecked original paper and it's indeed 8 bytes, sorry about that. Taking into account birthday paradox 64 bits it feels not enough to avoid collisions when you have millions of data entries.
